services:

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: "grafana/grafana"
    depends_on:
      - "prometheus"
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    links:
      - "prometheus:grafana"
