services:
  cors:
    build:
      context: cors
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  server:
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - "cors"
    ports:
      - "8080:80"
    links:
      - "server:cors"
