networks:
  my-network:
    driver: bridge

services:
  cors:
    build:
      context: cors
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - my-network
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - my-network
