services:

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  cors:
    build:
      context: cors
      dockerfile: Dockerfile
    ports:
      - "8081:80"
