FROM jenkins/jenkins:lts

# RUN sudo apt-get install docker.io
# RUN apt install jenkins-cli
# Install Jenkins CLI plugin
# RUN jenkins-cli plugins install http://updates.jenkins-ci.org/latest/jenkins-cli.hpi

# Define your plugins in a file (replace with your actual plugins)
# COPY plugins.txt /var/jenkins_home/plugins.txt

# Install plugins during startup
# RUN jenkins-cli plugins install --plugins-from=/var/jenkins_home/plugins.txt
