# this is the jenkins configuration
# You can get it from jenkins if you go to:
# Manage Jenkins -> Configuration as Code -> {View|Download} Configuration
jenkins:
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jnlpregistry: "name-of-your-registry"
      name: "name-of-your-k8s-cluster"
      namespace: "put-your-k8s-namespace-here"
      serverUrl: "192.167.45.6"
